---
version: "3.8"

volumes:
  postgres_data:
networks:
  net:

services:
  scheduler: &php_service
    build:
      dockerfile: ./docker/php/Dockerfile
      context: .
    user: "www-data"
    environment:
      DB_HOST: "$DB_HOST"
      DB_PORT: "$DB_PORT"
      DB_DATABASE: "$DB_DATABASE"
      DB_USERNAME: "$DB_USERNAME"
      DB_PASSWORD: "$DB_PASSWORD"
    volumes:
      - .:/app
    depends_on:
      - postgres
    networks: [net]
    command: ["php", "run", "scheduler"]

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "$DB_DATABASE"
      POSTGRES_USER: "$DB_USERNAME"
      POSTGRES_PASSWORD: "$DB_PASSWORD"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$DB_USERNAME -d $$DB_DATABASE"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - "./dev-data/init.sql:/docker-entrypoint-initdb.d/init.sql"
    networks: [net]
