---
version: "3.8"

volumes:
  postgres_data:
networks:
  net:

services:
  scheduler: &worker_service
    build:
      dockerfile: ./docker/php/Dockerfile
      context: .
    user: "www-data"
    environment:
      DB_HOST: "$DB_HOST"
      DB_PORT: "$DB_PORT"
      DB_DATABASE: "$DB_DATABASE"
      DB_USERNAME: "$DB_USERNAME"
      DB_PASSWORD: "$DB_PASSWORD"
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks: [net]
    command: ["php", "run", "run-scheduler"]

  queue-worker:
    <<: *worker_service
    deploy:
      replicas: 2
    command: ["php", "run", "run-queue-worker"]

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "$DB_DATABASE"
      POSTGRES_USER: "$DB_USERNAME"
      POSTGRES_PASSWORD: "$DB_PASSWORD"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - "./dev-data/init.sql:/docker-entrypoint-initdb.d/init.sql"
    networks: [net]
