---
version: "3.8"

volumes:
  mysql:

networks:
  net:

services:
  scheduler: &php_service
    build:
      dockerfile: ./docker/php/Dockerfile
      context: .
    user: "www-data"
    environment:
      APP_NAME: "expired-subscription-notification-service"
    volumes:
      - .:/app
    depends_on:
      - mysql
    networks: [net]
    command: ["php", "run", "scheduler"]

  mysql:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: "your_local_mysql_root_password"
      MYSQL_DATABASE: "your_local_database"
      MYSQL_USER: "your_local_username"
      MYSQL_PASSWORD: "your_local_password"
    ports:
      - "33060:3306"
    volumes:
      - mysql:/var/lib/mysql
    networks: [net]
