#!/usr/bin/env php
<?php

require_once './src/bootstrap.php';

$commandName = getCommandName();
$exitCode = runCommand($commandName);
$exitCode ? exit($exitCode) : exit();

function getCommandName(): string
{
    global $argv;

    if (!isset($argv[1])) {
        throw new RuntimeException(
            "The required argument command name is missed."
        );
    }

    return $argv[1];
}
